name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Check PUBLIC_BASE_API_URL is set
        run: |
          if [ -z "$PUBLIC_API_URL" ]; then
            echo "ERROR: PUBLIC_API_URL is not set. Please configure it in GitHub Secrets."
            exit 1
          fi
        env:
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
        env:
          PUBLIC_BASE_API_URL: ${{ secrets.PUBLIC_BASE_API_URL }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-dist
          path: dist/client
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dashboard-dist
          path: .

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        env:
          PUBLIC_API_URL: ${{ secrets.PUBLIC_API_URL }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_OCEAN_02128740F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_OCEAN_02128740F }}
          action: "close"
          app_location: "/"
